#include "scNameGenerator.hpp"
using namespace OPL::SimCreate;
using namespace std;

NameGenerator& NameGenerator::getNameGenerator()
{
  static NameGenerator onlyNameGenerator;
  return onlyNameGenerator;
}

NameGenerator::NameGenerator() : prefix("autogenerated_"), maxLength(8), firstLetter('a'), lastLetter('z')
{
  char firstName[maxLength];
  for(int i=0;i<maxLength;i++)
    firstName[i] = firstLetter;
  firstName[maxLength] = 0;
  lastName = string(firstName);
}

string NameGenerator::nextName()
{
  int i = maxLength-1;
  lastName[i]++;
  while(lastName[i] > lastLetter)
  {
    lastName[i] = firstLetter;
    i--;
    if(i<0) break;
    lastName[i]++;
  }
  
  ostringstream generatedName;
  generatedName << prefix << lastName;
  return generatedName.str();
}
